### ISSUE TITLE
Is there an ability to insert comments to a cell?

### ISSUE THREAD

**Issue by useit4me** [a-marenkov/gsheets#14]
Just wondering if there is a way to insert comments to a cell after reading the API docs found that it's called adding "notes".

**Comment by useit4me** [comment]
Just to add 
does this support copy also it breaks no while I try copyWorksheet.
im getting this error 
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: GSheetsException: Invalid requests[0].duplicateSheet: No sheet with id: 0
#0      checkResponse (package:gsheets/src/utils.dart:71:5)
#1      GSheets.batchUpdate (package:gsheets/src/gsheets.dart:228:5)
<asynchronous suspension>
#2      Spreadsheet.copyWorksheet (package:gsheets/src/gsheets.dart:379:36)
```


while running this code.

final copyFromTemplate = ss.copyWorksheet(workSheetTemplate, "title");

**Comment by a-marenkov** [comment]
> Just wondering if there is a way to insert comments to a cell after reading the API docs found that it's called adding "notes".

@useit4me 

Hi! Thanks for checking out gsheets library and providing your feedback!

No, currently ther is no support for inserting/reading notes. Thanks for suggestion! I'll try to add it following releases.

**Comment by a-marenkov** [comment]
> Just to add
> does this support copy also it breaks no while I try copyWorksheet.
> im getting this error
> 
> ```
> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: GSheetsException: Invalid requests[0].duplicateSheet: No sheet with id: 0
> #0      checkResponse (package:gsheets/src/utils.dart:71:5)
> #1      GSheets.batchUpdate (package:gsheets/src/gsheets.dart:228:5)
> <asynchronous suspension>
> #2      Spreadsheet.copyWorksheet (package:gsheets/src/gsheets.dart:379:36)
> ```
> 
> while running this code.
> 
> final copyFromTemplate = ss.copyWorksheet(workSheetTemplate, "title");

Can you please elaborate where does `workSheetTemplate` come from? 

The `copyWorksheet` method designed to copy existing worksheet.

**Comment by useit4me** [comment]
> > Just to add
> > does this support copy also it breaks no while I try copyWorksheet.
> > im getting this error
> > ```
> > [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: GSheetsException: Invalid requests[0].duplicateSheet: No sheet with id: 0
> > #0      checkResponse (package:gsheets/src/utils.dart:71:5)
> > #1      GSheets.batchUpdate (package:gsheets/src/gsheets.dart:228:5)
> > <asynchronous suspension>
> > #2      Spreadsheet.copyWorksheet (package:gsheets/src/gsheets.dart:379:36)
> > ```
> > 
> > 
> > while running this code.
> > final copyFromTemplate = ss.copyWorksheet(workSheetTemplate, "title");
> 
> Can you please elaborate where does `workSheetTemplate` come from?
> 
> The `copyWorksheet` method designed to copy existing worksheet.

so I have 2 sheets `workSheetTemplate` and another new sheet that I'm writing to, I'm trying to copy the template to a new sheet. and like you mentioned if it's designed to copy the existing worksheet then do you know of any other way to copy from another template to a new sheet.?

**Comment by a-marenkov** [comment]
> > > Just to add
> > > does this support copy also it breaks no while I try copyWorksheet.
> > > im getting this error
> > > ```
> > > [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: GSheetsException: Invalid requests[0].duplicateSheet: No sheet with id: 0
> > > #0      checkResponse (package:gsheets/src/utils.dart:71:5)
> > > #1      GSheets.batchUpdate (package:gsheets/src/gsheets.dart:228:5)
> > > <asynchronous suspension>
> > > #2      Spreadsheet.copyWorksheet (package:gsheets/src/gsheets.dart:379:36)
> > > ```
> > > 
> > > 
> > > while running this code.
> > > final copyFromTemplate = ss.copyWorksheet(workSheetTemplate, "title");
> > 
> > 
> > Can you please elaborate where does `workSheetTemplate` come from?
> > The `copyWorksheet` method designed to copy existing worksheet.
> 
> so I have 2 sheets `workSheetTemplate` and another new sheet that I'm writing to, I'm trying to copy the template to a new sheet. and like you mentioned if it's designed to copy the existing worksheet then do you know of any other way to copy from another template to a new sheet.?

Hi, sorry for delay with reply.

I'm not sure that understood you correctly. 

If you want to copy a worksheet from one spreadsheet to another you can use [this](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.sheets/copyTo), unfortunatly i have not supported it in gsheets yet, but i will.

If you want to copy a worksheet inside the same spreadsheet you can use [this method](https://pub.dev/documentation/gsheets/latest/gsheets/Spreadsheet/copyWorksheet.html).

Hope it helps. I'm not closing this issue and i'll keep you posted about updates regading missing features you have suggested.

**Comment by a-marenkov** [comment]
> Just to add
> does this support copy also it breaks no while I try copyWorksheet.
> im getting this error
> 
> ```
> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: GSheetsException: Invalid requests[0].duplicateSheet: No sheet with id: 0
> #0      checkResponse (package:gsheets/src/utils.dart:71:5)
> #1      GSheets.batchUpdate (package:gsheets/src/gsheets.dart:228:5)
> <asynchronous suspension>
> #2      Spreadsheet.copyWorksheet (package:gsheets/src/gsheets.dart:379:36)
> ```
> 
> while running this code.
> 
> final copyFromTemplate = ss.copyWorksheet(workSheetTemplate, "title");


@useit4me I rolled out pre-release version that covered copyTo functionality, i plan to release it soon but you can check:
```
dependencies:
  gsheets: ^0.2.5-dev.1
```
[Link to pub](https://pub.dev/packages/gsheets/versions/0.2.5-dev.1/changelog)
[copyTo](https://pub.dev/documentation/gsheets/0.2.5-dev.1/gsheets/Worksheet/copyTo.html)
[addFromSpreadsheet](https://pub.dev/documentation/gsheets/0.2.5-dev.1/gsheets/Spreadsheet/addFromSpreadsheet.html)

**Comment by useit4me** [comment]
no worries, im trying out and stuffs in my side I'm see if I can contribute.
