### ISSUE TITLE
How can I use streambuilder to display retrieved data?

### ISSUE THREAD

**Issue by shashikant-saini** [a-marenkov/gsheets#15]
I am currently building an app to manage expenses. It takes time to retrieve data and to display those on widgets. I am currently using Future Builder but to use it I have to refresh my page every time for the values to appear in the scaffold. Please help me with this.

```
//creating a variable to store query retrieve data
name = await sheet1.values.value(column: 1, row: x);
```
![Untitled](https://user-images.githubusercontent.com/44373858/83922170-80278880-a79d-11ea-9d67-839fd515aeb9.jpg)

```
//Creating` a Future Builder 
 Widget nameBuilder() {
    return FutureBuilder(
        builder: (context, AsyncSnapshot) {
          if (name != null) {
            return Text(
              '$name',
              style: kDrawerTS,
            );
          } else {
            return CircularProgressIndicator();
          }
        });
  }
```
![Untitled1](https://user-images.githubusercontent.com/44373858/83922286-ac430980-a79d-11ea-9678-62455213714a.jpg)

```
//Using the widget in Scaffold as child:
ListView(
          padding: const EdgeInsets.all(0.0),
          children: <Widget>[
            UserAccountsDrawerHeader(
              accountName: nameBuilder(),

```
![Untitled2](https://user-images.githubusercontent.com/44373858/83922314-ba912580-a79d-11ea-97aa-39cc778438ac.jpg)

**Comment by a-marenkov** [comment]
Hi! Thanks for checking out gsheets library!

To use StreamBuilder create StreamController and add new data once its updated.

Also consider using https://pub.dev/documentation/gsheets/latest/gsheets/WorksheetAsValues/row.html or https://pub.dev/documentation/gsheets/latest/gsheets/ValuesMapper/row.html to retrieve data in same row to reduce api calls and make application faster.

**Comment by a-marenkov** [comment]
Consider this issue solved.
