### ISSUE TITLE
Styling spreadsheet

### ISSUE THREAD

**Issue by lgarcin** [a-marenkov/gsheets#23]
Thanks for your package, it is very easy to use.
I was wondering if there was a way to add style to the spreadsheet ? (fonts, colors, etc...)

**Comment by a-marenkov** [comment]
Hi @lgarcin 
There is no support for formating and styling in **gsheets**. 

It should be possible with [Google Sheets API](https://developers.google.com/sheets/api) though. 

Thanks!
