### ISSUE TITLE
How to appendRow multiple times?

### ISSUE THREAD

**Issue by aldhosutra** [a-marenkov/gsheets#28]
Hello, i need to append multiple data in a single time, so i need to call appendRow in a loop. But, in the google sheet, i see that only one row being appended. Is this some kind of issue?

thanks, btw great project, very helpful

**Comment by a-marenkov** [comment]
Hi @aldhosutra

If you would like to append multiiple rows, you should use [appendRows](https://pub.dev/documentation/gsheets/latest/gsheets/WorksheetAsValues/appendRows.html).


Regarding your issue - most likely you've forgot to add `await` keyword. 
```
for/while loop {
   await sheet.values.appendRow(values);
}

```
But you should avoid using loops - there is going to be a request for each iteration.

Thanks for checking out gsheets!

**Comment by a-marenkov** [comment]
Here is an example
```
final values = [
['a', 'b', 'c'],
['1', '2', '3'],
['a1', 'b2', 'c3'],
];

await sheet.values.appendRows(values);
```

**Comment by aldhosutra** [comment]
Hello,
your code works perfectly

thanks, this is a great library, great help!
