### ISSUE TITLE
when I'm trying to store Data From google sheets i get this error:  ../../third_party/dart/runtime/vm/compiler/assembler/assembler_arm64.h: 168: error: unreachable code version=2.9.1 (stable) (Wed Aug 12 12:37:19 2020 +0200) on "android_arm64"

### ISSUE THREAD

**Issue by FarsFuad** [a-marenkov/gsheets#29]
this is my class where i store data from gsheet
class OrderDetails { String name,email,phone,order1,orderQ1,order1Price,order2,orderQ2,order2Price,order3,orderQ3,order3Price,order4,orderQ4,order4Price,order5,orderQ5,order5Price,order6,orderQ6,order6Price,order7,orderQ7,order7Price,order8,orderQ8,order8Price,order9,orderQ9,order9Price,order10,orderQ10,order10Price,city,address,locticon,totalOrderPrice,deliveryPrice,totalPrice,deliveryState,orderCreatedDate,orderDeliveryDate,orderState,note; int indexOfOrder; OrderDetails([this.name='null',this.email='null',this.phone='null',this.order1='null',this.orderQ1='null',this.order1Price='null',this.order2='null' ,this.orderQ2='null',this.order2Price='null',this.order3='null',this.orderQ3='null',this.order3Price='null',this.order4='null',this.orderQ4='null' ,this.order4Price='null',this.order5='null',this.orderQ5='null',this.order5Price='null',this.order6='null',this.orderQ6='null',this.order6Price='null',this.order7='null',this.orderQ7='null',this.order7Price='null',this.order8='null',this.orderQ8='null',this.order8Price='null',this.order9='null',this.orderQ9='null',this.order9Price='null',this.order10='null',this.orderQ10='null',this.order10Price='null',this.city='null' ,this.address='null',this.locticon='null',this.totalOrderPrice='null',this.deliveryPrice='null',this.totalPrice='null',this.deliveryState='null', this.orderCreatedDate='null',this.orderDeliveryDate='null',this.orderState='null',this.note='null',this.indexOfOrder=1])

here i insest my data.

order[i] = OrderDetails( orderColum[0], orderColum[1], orderColum[2], orderColum[3], orderColum[4], orderColum[5], orderColum[6], orderColum[7], orderColum[8], orderColum[9], orderColum[10], orderColum[11], orderColum[12], orderColum[13], orderColum[14], orderColum[15], orderColum[16], orderColum[17], orderColum[18], orderColum[19], orderColum[20], orderColum[21], orderColum[22], orderColum[23], orderColum[24], orderColum[25], orderColum[26], orderColum[27], orderColum[28], orderColum[29], orderColum[30], orderColum[31], orderColum[32], orderColum[33], orderColum[34], orderColum[35], orderColum[36], orderColum[37], orderColum[38], orderColum[39], orderColum[40], orderColum[41], orderColum[42], orderColum[43], int.parse(orderColum[44]), );

after that, i get this error.
`E/Dart (13709): ../../third_party/dart/runtime/vm/compiler/assembler/assembler_arm64.h: 168: error: unreachable code
E/DartVM (13709): version=2.9.1 (stable) (Wed Aug 12 12:37:19 2020 +0200) on "android_arm64"
E/DartVM (13709): pid=13709, thread=13799, isolate_group=main(0x7ef1e33300), isolate=main(0x7ef1efc600)
E/DartVM (13709): isolate_instructions=7e91d9c5e0, vm_instructions=7e91d9c5e0
E/DartVM (13709): pc 0x0000007e91eaadc4 fp 0x0000007ee8539660 /data/app/com.tng.manychatgooglesheet-oPatrWrONx8sGaDAGHOUog==/lib/arm64/libflutter.so+0x16e5dc4
E/DartVM (13709): -- End of DumpStackTrace
E/DartVM (13709): [exit : sp(0) fp(0x7ee853a4b8) pc(0)]
E/DartVM (13709): [stub : sp(0x7ee853a4c8) fp(0x7ee853a4e8) pc(0x7e7d101ab0)]
E/DartVM (13709): [dart : sp(0x7ee853a4f8) fp(0x7ee853a700) pc(0x7e5efc0508) package:manychatgooglesheet/Screens/AdminScreen/Search.dart__SearchState@34392600_refreshButton__async_op ]
E/DartVM (13709): [dart : sp(0x7ee853a710) fp(0x7ee853a780) pc(0x7e5d8cf838) dart:async_::_rootRunUnary@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853a790) fp(0x7ee853a7f8) pc(0x7e5d8cf5d4) dart:async::_rootRunUnary@4048458__rootRunUnary@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853a808) fp(0x7ee853a8a0) pc(0x7e5d8ceb38) dart:async__CustomZone@4048458_runUnary ]
E/DartVM (13709): [dart : sp(0x7ee853a8b0) fp(0x7ee853a8f0) pc(0x7e5d8ce564) dart:async__FutureListener@4048458_handleValue ]
E/DartVM (13709): [dart : sp(0x7ee853a900) fp(0x7ee853a968) pc(0x7e5d8cdff4) dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]
E/DartVM (13709): [dart : sp(0x7ee853a978) fp(0x7ee853a9f0) pc(0x7e5d8ccf48) dart:async__Future@4048458__propagateToListeners@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853aa00) fp(0x7ee853aa38) pc(0x7e5d8cb5e0) dart:async__Future@4048458__completeWithValue@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853aa48) fp(0x7ee853aa98) pc(0x7e6ca4ffd4) dart:async__AsyncAwaitCompleter@4048458_complete ]
E/DartVM (13709): [dart : sp(0x7ee853aaa8) fp(0x7ee853aad0) pc(0x7e6ca4f794) dart:async::_completeOnAsyncReturn@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853aae0) fp(0x7ee853ab98) pc(0x7e5efee450) package:gsheets/src/gsheets.dart_Worksheet__getAll@660007862__async_op ]
E/DartVM (13709): [dart : sp(0x7ee853aba8) fp(0x7ee853ac18) pc(0x7e5d8cf838) dart:async::_rootRunUnary@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853ac28) fp(0x7ee853ac90) pc(0x7e5d8cf5d4) dart:async::_rootRunUnary@4048458__rootRunUnary@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853aca0) fp(0x7ee853ad38) pc(0x7e5d8ceb38) dart:async__CustomZone@4048458_runUnary ]
E/DartVM (13709): [dart : sp(0x7ee853ad48) fp(0x7ee853ad88) pc(0x7e5d8ce564) dart:async__FutureListener@4048458_handleValue ]
E/DartVM (13709): [dart : sp(0x7ee853ad98) fp(0x7ee853ae00) pc(0x7e5d8cdff4) dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]
E/DartVM (13709): [dart : sp(0x7ee853ae10) fp(0x7ee853ae88) pc(0x7e5d8ccf48) dart:async__Future@4048458__propagateToListeners@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853ae98) fp(0x7ee853aed0) pc(0x7e5d8cb5e0) dart:async__Future@4048458__completeWithValue@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853aee0) fp(0x7ee853af30) pc(0x7e6ca4ffd4) dart:async__AsyncAwaitCompleter@4048458_complete ]
E/DartVM (13709): [dart : sp(0x7ee853af40) fp(0x7ee853af68) pc(0x7e6ca4f794) dart:async::_completeOnAsyncReturn@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853af78) fp(0x7ee853b000) pc(0x7eec374e88) package:http/src/response.dart_Response_fromStream__async_op ]
E/DartVM (13709): [dart : sp(0x7ee853b010) fp(0x7ee853b080) pc(0x7e5d8cf838) dart:async::_rootRunUnary@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853b090) fp(0x7ee853b0f8) pc(0x7e5d8cf5d4) dart:async::rootRunUnary@4048458__rootRunUnary@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853b108) fp(0x7ee853b1a0) pc(0x7e5d8ceb38) dart:async__CustomZone@4048458_runUnary ]
E/DartVM (13709): [dart : sp(0x7ee853b1b0) fp(0x7ee853b1f0) pc(0x7e5d8ce564) dart:async__FutureListener@4048458_handleValue ]
E/DartVM (13709): [dart : sp(0x7ee853b200) fp(0x7ee853b268) pc(0x7e5d8cdff4) dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]
E/DartVM (13709): [dart : sp(0x7ee853b278) fp(0x7ee853b2f0) pc(0x7e5d8ccf48) dart:async__Future@4048458__propagateToListeners@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853b300) fp(0x7ee853b338) pc(0x7e5d8cb5e0) dart:async__Future@4048458__completeWithValue@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853b348) fp(0x7ee853b388) pc(0x7e5d8cb0d8) dart:async__Future@4048458__asyncCompleteWithValue@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853b398) fp(0x7ee853b400) pc(0x7e6ca3c9e0) dart:async::_rootRun@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853b410) fp(0x7ee853b470) pc(0x7e6ca3c5f4) dart:async::rootRun@4048458__rootRun@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853b480) fp(0x7ee853b510) pc(0x7e6ca3b7b0) dart:async__CustomZone@4048458_run ]
E/DartVM (13709): [dart : sp(0x7ee853b520) fp(0x7ee853b580) pc(0x7e5d8cae28) dart:async__CustomZone@4048458_runGuarded ]
E/DartVM (13709): [dart : sp(0x7ee853b590) fp(0x7ee853b5d0) pc(0x7e5d8cac78) dart:async__CustomZone@4048458_bindCallbackGuarded ]
E/DartVM (13709): [dart : sp(0x7ee853b5e0) fp(0x7ee853b618) pc(0x7e5d8ca8b4) dart:async::_microtaskLoop@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853b628) fp(0x7ee853b658) pc(0x7e5d8ca438) dart:async::_startMicrotaskLoop@4048458 ]
E/DartVM (13709): [dart : sp(0x7ee853b668) fp(0x7ee853b698) pc(0x7e5d8ca31c) dart:async::__startMicrotaskLoop@4048458__startMicrotaskLoop@4048458 ]
E/DartVM (13709): [entry : sp(0x7ee853b6a8) fp(0x7ee853b768) pc(0x7e7d102084)]
F/libc (13709): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13799 (1.ui), pid 13709 (chatgooglesheet)

Build fingerprint: 'samsung/crownltexx/crownlte:10/QP1A.190711.020/N960FXXU6ETG3:user/release-keys'
Revision: '28'
ABI: 'arm64'
Timestamp: 2020-08-25 03:09:43+0200
pid: 13709, tid: 13799, name: 1.ui >>> com.tng.manychatgooglesheet <<<
uid: 10499
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
x0 0000000000000000 x1 00000000000035e7 x2 0000000000000006 x3 0000007ee85395d0
x4 0000000000000000 x5 0000000000000000 x6 0000000000000000 x7 0000800000000000
x8 00000000000000f0 x9 0000007f857a55e0 x10 0000000000000000 x11 0000000000000001
x12 0000007ee8538f58 x13 0000000000000003 x14 0000000000000000 x15 000054d6bffefb60
x16 0000007f858738c0 x17 0000007f85850880 x18 0000007e8f53a000 x19 00000000000000ac
x20 000000000000358d x21 00000000000000b2 x22 00000000000035e7 x23 00000000ffffffff
x24 0000000000000028 x25 0000007eea5377d0 x26 00000000ffffffff x27 0000007e9097440b
x28 ffffffffffffffff x29 0000007ee8539680
sp 0000007ee85395b0 lr 0000007f85804330 pc 0000007f85804360
backtrace:
#00 pc 0000000000083360 /apex/com.android.runtime/lib64/bionic/libc.so (abort+176) (BuildId: 13817077d0d892b63e2f982cf91d02fa)
#1 pc 00000000015d674c /data/app/com.tng.gg-oPatrWrONx8sGaDAGHOUog==/lib/arm64/libflutter.so (BuildId: eab9efb9274ed8ee8e31505362cd716ffe54b3e7)
#2 pc 00000000000f4e24 anonymous:7ee8445000
`

Flutter doc
`C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-GB)
• Flutter version 1.20.2 at C:\src\flutter
• Framework revision bbfbf17 (11 days ago), 2020-08-13 08:33:09 -0700
• Engine revision 9d5b21729f
• Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at C:\Users\fuad\AppData\Local\Android\sdk
• Platform android-29, build-tools 28.0.3
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
• All Android licenses accepted.

[√] Android Studio (version 4.0)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 48.1.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
• SM N960F (mobile) • 2b4c380c08017ece • android-arm64 • Android 10 (API 29)

• No issues found!`

any help please ?

**Comment by a-marenkov** [comment]
Hi @FarsFuad

As I understand, you've already found the cause of the problem [here] (https://github.com/flutter/flutter/issues/64526)?

**Comment by FarsFuad** [comment]
yes it was a problem with Dart VM, thanks btw 
you are the best , i really like your package <3
