### ISSUE TITLE
I cannot create a new spreadsheet using createSpreadsheet()

### ISSUE THREAD

**Issue by sathya4code** [a-marenkov/gsheets#30]
Hi,

I tried to create new Spreadsheet using  ` gsheets.createSpreadsheet('GSheet/GSheetTest');`. It is returning the data like id. But i cannot find the sheet in google drive. I cant understand whats going on. Anyone can help me?

**Comment by a-marenkov** [comment]
> GSheet/GSheetTest

Hi @sathya4code 

The spreadsheet created with service account belongs to it, so it should be found there.

What you're probably trying to achieve is done by following:
```dart
  final gsheets = GSheets(_credentials);
  final ss = await gsheets.createSpreadsheet('GSheet/GSheetTest');
  print(ss.id);
  await ss.share('{YOUR_EMAIL}@gmail.com', role: PermRole.owner);
```

Could you please let me know if it helps. Thanks!

**Comment by sathya4code** [comment]
> > GSheet/GSheetTest
> 
> Hi @sathya4code
> 
> The spreadsheet created with service account belongs to it, so it should be found there.
> 
> What you're probably trying to achieve is done by following:
> 
> ```dart
>   final gsheets = GSheets(_credentials);
>   final ss = await gsheets.createSpreadsheet('GSheet/GSheetTest');
>   print(ss.id);
>   await ss.share('{YOUR_EMAIL}@gmail.com', role: PermRole.owner);
> ```
> 
> Could you please let me know if it helps. Thanks!

Hi @a-marenkov,

Thank you for your response.
