### ISSUE TITLE
How convert Excel serial number date to DateTine 

### ISSUE THREAD

**Issue by JanRegent** [a-marenkov/gsheets#31]
Hi

i have column 
Date in sheet  -- in sheet.values I got as serial number
2019-05-15    -- 43600
2019-05-16   --  43601

I not found how convert serial no 43600 back to 2019-05-15

This is not bug. I am sorry.

Any ideas/solution/example for Dart?

Thanks a lot

**Comment by a-marenkov** [comment]
> Hi
> 
> i have column
> Date in sheet -- in sheet.values I got as serial number
> 2019-05-15 -- 43600
> 2019-05-16 -- 43601
> 
> I not found how convert serial no 43600 back to 2019-05-15
> 
> This is not bug. I am sorry.
> 
> Any ideas/solution/example for Dart?
> 
> Thanks a lot

Hi @JanRegent 

Don't be sorry, dates in google sheets are quite odd...

Try using these two methods:

```dart
const gsDateBase = 2209161600 / 86400;
const gsDateFactor = 86400000;

double dateToGsheets(DateTime dateTime, {bool localTime = true}) {
  final offset = dateTime.millisecondsSinceEpoch / gsDateFactor;
  final shift = localTime ? dateTime.timeZoneOffset.inHours / 24 : 0;
  return gsDateBase + offset + shift;
}

DateTime dateFromGsheets(String value, {bool localTime = true}) {
  final date = double.tryParse(value ?? '');
  if (date == null) return null;
  final millis = (date - gsDateBase) * gsDateFactor;
  return DateTime.fromMillisecondsSinceEpoch(millis.toInt(), isUtc: localTime);
}
```

Please let me know if it helps!

**Comment by JanRegent** [comment]
QAlegander

That's exactly what I was looking for!
2019-05-15 00:00:00.000Z
2019-05-16 00:00:00.000Z

There were only examples for JavaScript on the web with libraries unknown to me in Dart
Thank you for your amazing package
Perhaps I will present an application based on it soon :-)

**Comment by canastro** [comment]
I know this is an old issue, but if someone happens to come across this, theres only a minor precision issue. instead of doing:

```dart
  return DateTime.fromMillisecondsSinceEpoch(millis.toInt(), isUtc: localTime);
````

You should do:

```
  return DateTime.fromMillisecondsSinceEpoch(millis.round(), isUtc: localTime);
```

**Comment by Mohammed187** [comment]
> > Hi
> > i have column
> > Date in sheet -- in sheet.values I got as serial number
> > 2019-05-15 -- 43600
> > 2019-05-16 -- 43601
> > I not found how convert serial no 43600 back to 2019-05-15
> > This is not bug. I am sorry.
> > Any ideas/solution/example for Dart?
> > Thanks a lot
> 
> Hi @JanRegent
> 
> Don't be sorry, dates in google sheets are quite odd...
> 
> Try using these two methods:
> 
> ```dart
> const gsDateBase = 2209161600 / 86400;
> const gsDateFactor = 86400000;
> 
> double dateToGsheets(DateTime dateTime, {bool localTime = true}) {
>   final offset = dateTime.millisecondsSinceEpoch / gsDateFactor;
>   final shift = localTime ? dateTime.timeZoneOffset.inHours / 24 : 0;
>   return gsDateBase + offset + shift;
> }
> 
> DateTime dateFromGsheets(String value, {bool localTime = true}) {
>   final date = double.tryParse(value ?? '');
>   if (date == null) return null;
>   final millis = (date - gsDateBase) * gsDateFactor;
>   return DateTime.fromMillisecondsSinceEpoch(millis.toInt(), isUtc: localTime);
> }
> ```
> 
> Please let me know if it helps!

Thanks a lot. I was looking for this solution everywhere.

**Comment by jamesderlin** [comment]
> ```dart
> DateTime dateFromGsheets(String value, {bool localTime = true}) {
>   final date = double.tryParse(value ?? '');
>   if (date == null) return null;
>   final millis = (date - gsDateBase) * gsDateFactor;
>   return DateTime.fromMillisecondsSinceEpoch(millis.toInt(), isUtc: localTime);
> }
> ```

The `localTime` parameter seems backward.  Shouldn't it either be:
```dart
DateTime dateFromGsheets(String value, {bool isUtc = false}) {
  ...
  return DateTime.fromMillisecondsSinceEpoch(..., isUtc: isUtc);
}
```
or:
```dart
DateTime dateFromGsheets(String value, {bool localTime = true}) {
  ...
  return DateTime.fromMillisecondsSinceEpoch(..., isUtc: !localTime);
}
```
