### ISSUE TITLE
Use api key or user token to access the sheets

### ISSUE THREAD

**Issue by saeedek** [a-marenkov/gsheets#35]
Hi,
I didn't see any other example, but is it possible not to use a service account and instead use an API key or user token to access the sheets?

Thanks.

**Comment by a-marenkov** [comment]
> Hi,
> I didn't see any other example, but is it possible not to use a service account and instead use an API key or user token to access the sheets?
> 
> Thanks.

Hi @saeedek,

Sorry for the delay with reply.

Currently only service account is supported.

gsheets uses [googleapis_auth](https://pub.dev/packages/googleapis_auth) under the hood, so it's possible to add other options available in the package, but i'm not sure that they are practical. The API key flow will give access to public data only (according to the docs).

**Comment by seanocali** [comment]
> > Hi,
> > I didn't see any other example, but is it possible not to use a service account and instead use an API key or user token to access the sheets?
> > Thanks.
> 
> Hi @saeedek,
> 
> Sorry for the delay with reply.
> 
> Currently only service account is supported.
> 
> gsheets uses [googleapis_auth](https://pub.dev/packages/googleapis_auth) under the hood, so it's possible to add other options available in the package, but i'm not sure that they are practical. The API key flow will give access to public data only (according to the docs).

Why is this not practical? Accessing public sheets is a very valid use case.
