### ISSUE TITLE
Gsheets doesn't support null safety

### ISSUE THREAD

**Issue by AnavrinApps** [a-marenkov/gsheets#38]
Hi,
Can you please update this dependency to support null safety?

**Comment by a-marenkov** [comment]
@AnavrinApps hi! Thanks for filing the issue i see that googleapis, googleapis_auth already support null safety, so gsheets can be migrated. I'll try find the time to migrate this week.

**Comment by a-marenkov** [comment]
I've run migration tool and made a pre-release, please check 0.3.0-nullsafety.0 version

I do not recommend using this version in production. I have not been able to test it properly yet.

**Comment by AnavrinApps** [comment]
Hey, so I tried that version & I get the following error - 

[testapp] flutter pub get
Running "flutter pub get" in testapp...     
Because gsheets >=0.3.0-nullsafety.0 depends on http ^0.13.0 and firebase >=5.0.3 <9.0.0 depends on http >=0.11.3 <0.13.0, gsheets >=0.3.0-nullsafety.0 is incompatible with firebase >=5.0.3 <9.0.0.
And because firebase_analytics_web 0.2.0 depends on firebase ^7.3.0 and no versions of firebase_analytics_web match >0.2.0 <0.3.0, gsheets >=0.3.0-nullsafety.0 is incompatible with firebase_analytics_web ^0.2.0.
And because firebase_analytics 7.1.0 depends on firebase_analytics_web ^0.2.0 and no versions of firebase_analytics match >7.1.0 <8.0.0, gsheets >=0.3.0-nullsafety.0 is incompatible with firebase_analytics ^7.1.0.
So, because testapp depends on both firebase_analytics ^7.1.0 and gsheets ^0.3.0-nullsafety.0, version solving failed.

pub get failed (1; So, because testapp depends on both firebase_analytics ^7.1.0 and gsheets ^0.3.0-nullsafety.0, version solving failed.)
exit code 1

**Comment by a-marenkov** [comment]
> Hey, so I tried that version & I get the following error - 
> 
> [testapp] flutter pub get
> Running "flutter pub get" in testapp...     
> Because gsheets >=0.3.0-nullsafety.0 depends on http ^0.13.0 and firebase >=5.0.3 <9.0.0 depends on http >=0.11.3 <0.13.0, gsheets >=0.3.0-nullsafety.0 is incompatible with firebase >=5.0.3 <9.0.0.
> And because firebase_analytics_web 0.2.0 depends on firebase ^7.3.0 and no versions of firebase_analytics_web match >0.2.0 <0.3.0, gsheets >=0.3.0-nullsafety.0 is incompatible with firebase_analytics_web ^0.2.0.
> And because firebase_analytics 7.1.0 depends on firebase_analytics_web ^0.2.0 and no versions of firebase_analytics match >7.1.0 <8.0.0, gsheets >=0.3.0-nullsafety.0 is incompatible with firebase_analytics ^7.1.0.
> So, because testapp depends on both firebase_analytics ^7.1.0 and gsheets ^0.3.0-nullsafety.0, version solving failed.
> 
> pub get failed (1; So, because testapp depends on both firebase_analytics ^7.1.0 and gsheets ^0.3.0-nullsafety.0, version solving failed.)
> exit code 1
> 

Well, I can try to lower version of http package, but it will force non sound null safety in gsheets. I think it's better to wait till firebase analytics get migrated.

**Comment by AnavrinApps** [comment]
Flutter pub upgrade resolved it, hoping you'll migrate when you have the time. Thank you for your help :D
