### ISSUE TITLE
Update gsheets v0.2.6 constraints 

### ISSUE THREAD

**Issue by AnavrinApps** [a-marenkov/gsheets#39]
Hi, so I know that your null safety version isn't ready for production but could you update your dependency plugins so that it is compatible with firebase_auth? Thanks.

Because gsheets >=0.2.6 <0.3.0-nullsafety.0 depends on http ^0.12.2 which depends on http_parser >=0.0.1 <4.0.0, gsheets >=0.2.6 <0.3.0-nullsafety.0 requires http_parser >=0.0.1 <4.0.0.

And because firebase_auth_web >=1.0.0 depends on http_parser ^4.0.0, gsheets >=0.2.6 <0.3.0-nullsafety.0 is incompatible with firebase_auth_web >=1.0.0.
And because firebase_auth 1.0.1 depends on firebase_auth_web ^1.0.1 and no versions of firebase_auth match >1.0.1 <2.0.0, gsheets >=0.2.6 <0.3.0-nullsafety.0 is incompatible with firebase_auth ^1.0.1.

So, because test_app depends on both firebase_auth ^1.0.1 and gsheets ^0.2.6, version solving failed.
pub get failed (1; So, because test_app depends on both firebase_auth ^1.0.1 and gsheets ^0.2.6, version solving failed.)
exit code 1

**Comment by a-marenkov** [comment]
> Hi, so I know that your null safety version isn't ready for production but could you update your dependency plugins so that it is compatible with firebase_auth? Thanks.
> 
> Because gsheets >=0.2.6 <0.3.0-nullsafety.0 depends on http ^0.12.2 which depends on http_parser >=0.0.1 <4.0.0, gsheets >=0.2.6 <0.3.0-nullsafety.0 requires http_parser >=0.0.1 <4.0.0.
> 
> 
> And because firebase_auth_web >=1.0.0 depends on http_parser ^4.0.0, gsheets >=0.2.6 <0.3.0-nullsafety.0 is incompatible with firebase_auth_web >=1.0.0.
> And because firebase_auth 1.0.1 depends on firebase_auth_web ^1.0.1 and no versions of firebase_auth match >1.0.1 <2.0.0, gsheets >=0.2.6 <0.3.0-nullsafety.0 is incompatible with firebase_auth ^1.0.1.
> 
> So, because test_app depends on both firebase_auth ^1.0.1 and gsheets ^0.2.6, version solving failed.
> pub get failed (1; So, because test_app depends on both firebase_auth ^1.0.1 and gsheets ^0.2.6, version solving failed.)
> exit code 1

Hi, sure!

My bad, I should have done it.

I'll do it later on today. 

Thanks for letting me know.

**Comment by AnavrinApps** [comment]
Ok :)

**Comment by a-marenkov** [comment]
> Ok :)

Hi, unfortunately i cannot just update dependencies, i have to migrate almost everything. Once i have enough time i'll do it.

**Comment by AnavrinApps** [comment]
I have made a workaround version with the updated dependencies, you can check it out here if you would like to use it - https://github.com/AnavrinApps/gsheets

**Comment by AnavrinApps** [comment]
Hi, just wanted to know do you plan on maintaining the dependency, its been over a month since an update and the dependency can currently isn't compatible with Flutter anymore?

**Comment by a-marenkov** [comment]
Hi! 
In next 2 weeks I plan to properly migrate gsheets to null safety. 
After that, I plan to support further changes to flutter and dart sdk. Also I'll fix any bugs. 
I do not have plans to develop any big features for gsheets, however. 
Sent from Yahoo Mail on Android 
 
  On Sat, Apr 17, 2021 at 13:38, ***@***.***> wrote:   


Hi, just wanted to know do you plan on maintaining the dependency, its been over a month since an update and the dependency can currently isn't compatible with Flutter anymore?

**Comment by AnavrinApps** [comment]
Great, thanks for the update.
