### ISSUE TITLE
Get image from the cell

### ISSUE THREAD

**Issue by pein95** [a-marenkov/gsheets#4]
There is an ability to insert images to the cells. Will be great if this lib can fetch this image.

**Comment by a-marenkov** [comment]
Hi! Thanks for checking out gsheets library and providing your feedback!


I'm not sure that there's a way to get embedded in a cell image with Google Sheets API v4.

If you know, please let me know how or provide me with link to the documentation.


However, if you add images in cells with formulas, like following: 

_**=image("https://dart.dev/assets/shared/dart/logo+text/horizontal/white-e71fb382ad5229792cc704b3ee7a88f8013e986d6e34f0956d89c453b454d0a5.svg")**_

It can be easely fetched. Here's a snippet:
(lets assume that you have added formula into A1)

```
void main() async {
  final gsheets = GSheets(_credentials);
  final ss = await gsheets.spreadsheet(
    _spreadsheetId,
    render: ValueRenderOption.formula,
  );
  final sheet = await ss.worksheetByTitle('example');
  // prints the formula, link can be easily extracted
  print(await sheet.values.value(column: 1, row: 1));
}
```
Could you please let me know if it works for you.

Thanks!

**Comment by piecubed** [comment]
Haven't checked if this works yet, but images in cells could be [a hyperlink](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/cells#celldata)

**Comment by a-marenkov** [comment]
> Haven't checked if this works yet, but images in cells could be [a hyperlink](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/cells#celldata)

Nice, it's might be the way. I'll check later on today. Thanks!

**Comment by a-marenkov** [comment]
I checked  [a hyperlink](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/cells#celldata) and it didn't work, so i'm closing the issue since there's no known way to do that.
