### ISSUE TITLE
Spreadsheet id instructions

### ISSUE THREAD

**Issue by alexeyselina** [a-marenkov/gsheets#44]
Please consider changing instruction for getting spreadsheet id from the link:

https://docs.google.com/spreadsheets/d/spreadsheetId/edit#gid=1590950017

By mistake at first I tried this 'gid' because it marked with color. 
Maybe put it like

https://docs.google.com/spreadsheets/d/YOUR_SPREADSHEET_ID/edit#gid=doesntmatter

**Comment by a-marenkov** [comment]
Hi @alexeyselina 

Thanks for the suggestion. I've removed all confusing instructions from readme, fixed link to example and added comments in example code with your suggestion.

**Comment by a-marenkov** [comment]
done in https://github.com/a-marenkov/gsheets/pull/46

**Comment by a-marenkov** [comment]
done in #46
