### ISSUE TITLE
Import/Export functionality

### ISSUE THREAD

**Issue by JTPenn-EG** [a-marenkov/gsheets#47]
Adding import/export functionality from csv/xlsx will be extremely helpful in alot of situations, for example when you need to give offline versions of the spreadsheet to your customers which they can edit however they want and receive their edited version and decide whether to import it to the original spreadsheet or not.

**Comment by a-marenkov** [comment]
@JTPenn-EG Hi, what api do you have in mind?

**Comment by nsvetlakov** [comment]
Good afternoon,
How can I download a table(sheet) in pdf format?

**Comment by a-marenkov** [comment]
> Good afternoon,
> How can I download a table(sheet) in pdf format?
> Or send only a sheet in pdf format to the mail?
> 

Hi @nsvetlakov

There's no such functionality in gsheets.

You can try to download spreadsheet in csv (maybe in pdf also) see  https://stackoverflow.com/questions/11619805/using-the-google-drive-api-to-download-a-spreadsheet-in-csv-format/51235960#51235960

**Comment by a-marenkov** [comment]
> Good afternoon,
> How can I download a table(sheet) in pdf format?
> Or send only a sheet in pdf format to the mail?

Hi @nsvetlakov i tried to export file and seems to work even with private spreadsheets

added following method https://pub.dev/documentation/gsheets/latest/gsheets/Spreadsheet/export.html

**Comment by nsvetlakov** [comment]
> > Good afternoon,
> > How can I download a table(sheet) in pdf format?
> > Or send only a sheet in pdf format to the mail?
> 
> Hi @nsvetlakov i tried to export file and seems to work even with private spreadsheets
> 
> added following method https://pub.dev/documentation/gsheets/latest/gsheets/Spreadsheet/export.html

Great,
You will need to redo it in my application.

And so I found a way to download pdf)))

I copied the sheet to another table and downloaded it using the curl link and then saved it.

**Comment by nsvetlakov** [comment]
> > Good afternoon,
> > How can I download a table(sheet) in pdf format?
> > Or send only a sheet in pdf format to the mail?
> 
> Hi @nsvetlakov i tried to export file and seems to work even with private spreadsheets
> 
> added following method https://pub.dev/documentation/gsheets/latest/gsheets/Spreadsheet/export.html

Awesome!!!
Thank you very much!!!
