### ISSUE TITLE
Cannot import package

### ISSUE THREAD

**Issue by Scylla2020** [a-marenkov/gsheets#48]
I've installed the library but this line still shows an error `import 'package:gsheets/gsheets.dart';` Also the tutorial about getting credentials doesnt show where the other values like client_id, client_x509_cert_url come from? Package is pretty much unusable at this time

**Comment by a-marenkov** [comment]
> I've installed the library but this line still shows an error `import 'package:gsheets/gsheets.dart';` Also the tutorial about getting credentials doesnt show where the other values like client_id, client_x509_cert_url come from? Package is pretty much unusable at this time

Hi @Scylla2020 

I'm sorry that you had bad experience setting up the [gsheets](https://pub.dev/packages/gsheets).

Regarding credentials. What tutorial are you referring to? I have placed the [link to the tutorial "How to get credentials"](https://medium.com/@a.marenkov/how-to-get-credentials-for-google-sheets-456b7e88c430) in readme and example comments. 


Regarding import error. Could you please elaborate on the error? Does dart analysis say what the error is? What version of dart/flutter sdk you're using and what version of gsheets?

**Comment by a-marenkov** [comment]
Closing due to no reply
