### ISSUE TITLE
Unhandled Exception: Invalid argument(s): The given string does not have the correct begin/end markers expected in a PEM file.

### ISSUE THREAD

**Issue by bremington** [a-marenkov/gsheets#49]
Hi, I am using your example with my spreadsheet id. I used the _credentials const from your example, but I get this error. In reviewing your Medium article, none of your points align with the credential field names. Am I to fill out the project_id, private_key_id, etc that are "" ? If I need to complete these where is the correlation of the Google API details and the credential list? As an example I have an email assigned to the service account..is this "client_email"? 

Thank you

BTW - this works perfect in gsheets get with just the spreadsheet id..but not in your package.

**Comment by a-marenkov** [comment]
@bremington Hi
What article are you referring to? I have placed the [link to the tutorial "How to get credentials"](https://medium.com/@a.marenkov/how-to-get-credentials-for-google-sheets-456b7e88c430) in readme and example comments. 

If you follow the steps, you'll have your credentials json downloaded at the step 4.

**Comment by a-marenkov** [comment]
Closing due to no reply
