### ISSUE TITLE
I am Trying Row 3 And Column 2 Value insert in sheet but it is not working, and i am using insertRowByKey Method

### ISSUE THREAD

**Issue by neel-vaghani** [a-marenkov/gsheets#50]

**Comment by a-marenkov** [comment]
Hi @neel-vaghani 

I did not understand what are you trying to do, and what is not working. Could you please elaborate on your use case? 

If you know indices you should use https://pub.dev/documentation/gsheets/latest/gsheets/WorksheetAsValues/insertValue.html

**Comment by a-marenkov** [comment]
Closing due to no reply
