### ISSUE TITLE
Error invalid_grant 

### ISSUE THREAD

**Issue by almog228** [a-marenkov/gsheets#51]
Hello everyone, after a few days that everything worked fine I am trying to connect to Google Shits I got the following glitch:

Init Error: Exception: Unable to obtain credentials. Error: invalid_grant.

My token address is:
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
   "token_uri": "https://oauth2.googleapis.com/token",

What am I supposed to do?

**Comment by a-marenkov** [comment]
> Hello everyone, after a few days that everything worked fine I am trying to connect to Google Shits I got the following glitch:
> 
> Init Error: Exception: Unable to obtain credentials. Error: invalid_grant.
> 
> My token address is:
>   "auth_uri": "https://accounts.google.com/o/oauth2/auth",
>    "token_uri": "https://oauth2.googleapis.com/token",
> 
> What am I supposed to do?

Hi @almog228

This seems to be a credentials issue, not a gsheets.

There are many different reasons why you're might be getting this error.

Most likely either the owner of the spreadsheet has revoked the permission, or has reset/recovered his/her Google password.

**Comment by almog228** [comment]
> This seems to be a credentials issue, not a gsheets.
> 
> There are many different reasons why you're might be getting this error.
> 
> Most likely either the owner of the spreadsheet has revoked the permission, or has reset/recovered his/her Google password.

Ok ,  i check this . Tnx

**Comment by a-marenkov** [comment]
> Ok ,  i check this . Tnx

👍 Let me know if it helps

**Comment by a-marenkov** [comment]
> > This seems to be a credentials issue, not a gsheets.
> > There are many different reasons why you're might be getting this error.
> > Most likely either the owner of the spreadsheet has revoked the permission, or has reset/recovered his/her Google password.
> 
> Ok , i check this . Tnx

Hi @almog228 ! Did you solve the problem?

**Comment by almog228** [comment]
Yes, the problem was with the Android emulator.  I did a reset for him and now everything is working fine.  Thank you.
