### ISSUE TITLE
Feature Request: using named-range to read cell values

### ISSUE THREAD

**Issue by SDCode1** [a-marenkov/gsheets#52]
Hi, I am new here. I am using gsheets API for a dart/flutter project app. Everything is working good, thanks for the API.

Is it possible to use named-ranges with this API? 
If not, can this feature be added? I have limited knowledge, but I am willing to help.

**Comment by a-marenkov** [comment]
> Hi, I am new here. I am using gsheets API for a dart/flutter project app. Everything is working good, thanks for the API.
> 
> Is it possible to use named-ranges with this API? 
> If not, can this feature be added? I have limited knowledge, but I am willing to help.

Hi @SDCode1

What do you mean by "named-ranges"?

Do you mean using A1 notation for column/row?

**Comment by a-marenkov** [comment]
Closing due to no reply

In gsheets 0.3.2 A1Ref class was added might be useful for such cases

**Comment by SDCode1** [comment]
Here is an example of named-range:

cell A1 can have an alias (named-range) of 'Example'.

In formulas, we can refer to A1 as 
=A1+B1
or
=Example+B1

Link to [named-range](https://support.google.com/docs/answer/63175?hl=en&co=GENIE.Platform%3DDesktop)
