### ISSUE TITLE
Exception Occurred. _CastError

### ISSUE THREAD

**Issue by elomayry** [a-marenkov/gsheets#57]
Hello ,
i was using this package perfectly but recently this error appears i create an new project for test but it gave the same problem
![as](https://user-images.githubusercontent.com/43796833/136033381-bf007a12-44f6-43af-addb-31f6fd23f1a3.png)

**Comment by a-marenkov** [comment]
Hi @elomayry 

There were no changes to gsheets and i cannot reproduce the error.

Can you please provide the stack trace and minimal example that reproduces the error?

**Comment by a-marenkov** [comment]
it does not look like the issue is with the gsheets
