### ISSUE TITLE
Is there any equivalent of getDisplayValues() here? 

### ISSUE THREAD

**Issue by alX-u** [a-marenkov/gsheets#64]
The thing is I'm saving dates in my spreadsheet, and when I perform the worksheet.values.map.lastRow() to get the last added row info, I obtain the date with a wrong format. I want it as a string, but given that Gsheets views it as a date/number. If the date is 2021/12/22, for example, I obtain something like 445040 when reading it with lastRow(). Is there a way to obtain the value as a string? Thanks.

**Comment by a-marenkov** [comment]
Hi @alX-u 

ValueRenderOption might help you, but i would recommend you instead of reading date as a string, parsing timestamp value into DateTime.

Try using these two methods:

```dart
const gsDateBase = 2209161600 / 86400;
const gsDateFactor = 86400000;

double dateToGsheets(DateTime dateTime, {bool localTime = true}) {
  final offset = dateTime.millisecondsSinceEpoch / gsDateFactor;
  final shift = localTime ? dateTime.timeZoneOffset.inHours / 24 : 0;
  return gsDateBase + offset + shift;
}

DateTime dateFromGsheets(String value, {bool localTime = true}) {
  final date = double.tryParse(value ?? '');
  if (date == null) return null;
  final millis = (date - gsDateBase) * gsDateFactor;
  return DateTime.fromMillisecondsSinceEpoch(millis.round(), isUtc: localTime);
}
```

**Comment by alX-u** [comment]
> Hi @alX-u
> 
> ValueRenderOption might help you, but i would recommend you instead of reading date as a raw string, parsing timestamp value into DateTime.
> 
> Try using these two methods:
> 
> ```dart
> const gsDateBase = 2209161600 / 86400;
> const gsDateFactor = 86400000;
> 
> double dateToGsheets(DateTime dateTime, {bool localTime = true}) {
>   final offset = dateTime.millisecondsSinceEpoch / gsDateFactor;
>   final shift = localTime ? dateTime.timeZoneOffset.inHours / 24 : 0;
>   return gsDateBase + offset + shift;
> }
> 
> DateTime? dateFromGsheets(String value, {bool localTime = true}) {
>   final date = double.tryParse(value);
>   if (date == null) return null;
>   final millis = (date - gsDateBase) * gsDateFactor;
>   return DateTime.fromMillisecondsSinceEpoch(millis.round(), isUtc: localTime);
> }
> ```

Yes, this works amazingly, thanks a lot!
