### ISSUE TITLE
Get row index by value

### ISSUE THREAD

**Issue by fabfaby** [a-marenkov/gsheets#7]
Is there a way to get the index of the row by searching a column for a certain value?

**Comment by a-marenkov** [comment]
@fabfaby 

Hi! Thanks for checking out gsheets library!

Yes, try using `rowIndexOf`.

```
await sheet.values.rowIndexOf('some value', inColumn: 2);
```

Here is the link to doc https://pub.dev/documentation/gsheets/latest/gsheets/WorksheetAsValues/rowIndexOf.html

**Comment by fabfaby** [comment]
Perfect, exactly what I was looking for..  :-)
