### ISSUE TITLE
Version 0.4.0 is not AOT compatible

### ISSUE THREAD

**Issue by dluksza** [a-marenkov/gsheets#72]
New googleapis_auth is using `dart:html` and `dart:js` which makes AOT compilation impossible.

Would it be possible to somehow exclude those or replace for AOT compilation?

**Comment by a-marenkov** [comment]
> New googleapis_auth is using `dart:html` and `dart:js` which makes AOT compilation impossible.
> 
> 
> 
> Would it be possible to somehow exclude those or replace for AOT compilation?

Hi @dluksza 

I think I know what causes the issue, I'll try to fix it later on today.

Thanks for the report

**Comment by a-marenkov** [comment]
> New googleapis_auth is using `dart:html` and `dart:js` which makes AOT compilation impossible.
> 
> Would it be possible to somehow exclude those or replace for AOT compilation?

@dluksza can you please check whether you have the same problem with `gsheets: ^0.4.1-rc.1`

**Comment by dluksza** [comment]
@a-marenkov `0.4.1-rc.2` works fine! thanks!

BTW. How this was fixed?

**Comment by a-marenkov** [comment]
> @a-marenkov `0.4.1-rc.2` works fine! thanks!

I have released 0.4.1 with the fix

> BTW. How this was fixed?

I've been experimenting with implicit browser flow without using conditional imports. So as quickfix i removed `auth_browser` imports

**Comment by dluksza** [comment]
Thanks!
