### ISSUE TITLE
0.4.1: '_GrowableList<dynamic>' is not a subtype of type 'List<Map<String, dynamic>>?'

### ISSUE THREAD

**Issue by dluksza** [a-marenkov/gsheets#73]
Does 0.4.1 require any (breaking) API changes? I've got this error:
```
type '_GrowableList<dynamic>' is not a subtype of type 'List<Map<String, dynamic>>?'
#0      new SpreadsheetData._fromJson (package:gsheets/src/gsheets.dart:334)
#1      new Spreadsheet._fromJson (package:gsheets/src/gsheets.dart:435)
#2      GSheets.spreadsheet (package:gsheets/src/gsheets.dart:207)
```
on the first attempt to persist data in gsheet.

Haven't changed anything in my code after bumping the version from 0.3.2 to 0.4.1. Also, everything compiled without any type errors, therefore would assume that it should work.

**Comment by a-marenkov** [comment]
> Does 0.4.1 require any (breaking) API changes? I've got this error:
> 
> ```
> 
> type '_GrowableList<dynamic>' is not a subtype of type 'List<Map<String, dynamic>>?'
> 
> #0      new SpreadsheetData._fromJson (package:gsheets/src/gsheets.dart:334)
> 
> #1      new Spreadsheet._fromJson (package:gsheets/src/gsheets.dart:435)
> 
> #2      GSheets.spreadsheet (package:gsheets/src/gsheets.dart:207)
> 
> ```
> 
> on the first attempt to persist data in gsheet.
> 
> 
> 
> Haven't changed anything in my code after bumping the version from 0.3.2 to 0.4.1. Also, everything compiled without any type errors, therefore would assume that it should work.

Hi! I'll look into it, seems that there's a bug

Thanks

**Comment by a-marenkov** [comment]
> #0      new SpreadsheetData._fromJson (package:gsheets/src/gsheets.dart:334)

Hi, can you please check if you have problem on `0.4.2-rc.2`

**Comment by dluksza** [comment]
Couldn't reproduce the same error on `0.4.2`. Thank you!
