### ISSUE TITLE
0.4.1 Error while init gsheets

### ISSUE THREAD

**Issue by fedesenmartin** [a-marenkov/gsheets#74]
I configured my credentials ,added the library to project and init it with my sheet id and creds.

First 
` final gsheets = GSheets(_credentials);
`
seems no problem here(at least the console is not showing errors)

But after 
` final ss = await gsheets.spreadsheet(_spreadsheetId)
`

Im getting this error in console
`Error: Expected a value of type 'List<Map<String, dynamic>>?', but got one of type 'List<dynamic>'`

BTW Im trying on flutter web

**Comment by a-marenkov** [comment]
> I configured my credentials ,added the library to project and init it with my sheet id and creds.
> 
> 
> 
> First 
> 
> ` final gsheets = GSheets(_credentials);
> 
> `
> 
> seems no problem here(at least the console is not showing errors)
> 
> 
> 
> But after 
> 
> ` final ss = await gsheets.spreadsheet(_spreadsheetId)
> 
> `
> 
> 
> 
> Im getting this error in console
> 
> `Error: Expected a value of type 'List<Map<String, dynamic>>?', but got one of type 'List<dynamic>'`
> 
> 
> 
> BTW Im trying on flutter web 

Hi! I'll look into it

**Comment by a-marenkov** [comment]
> I configured my credentials ,added the library to project and init it with my sheet id and creds.
> 
> First `final gsheets = GSheets(_credentials);` seems no problem here(at least the console is not showing errors)
> 
> But after `final ss = await gsheets.spreadsheet(_spreadsheetId)`
> 
> Im getting this error in console `Error: Expected a value of type 'List<Map<String, dynamic>>?', but got one of type 'List<dynamic>'`
> 
> BTW Im trying on flutter web

Hi, can you please check if you have problem on 0.4.2-rc.1

**Comment by fedesenmartin** [comment]
@a-marenkov 
Hi! checked with 0.4.2. It seems fixed! 
Awesome! Thanks
