### ISSUE TITLE
Different response time

### ISSUE THREAD

**Issue by EnesMBatur** [a-marenkov/gsheets#76]
I am using the gsheets library in flutter. While my sheet is open and using it, api calls return fast response, but even if I use a server, api calls come very late after a certain period of time. how can i solve this problem?

**Comment by a-marenkov** [comment]
@EnesMBatur 

Hi! Sorry i did not understand the case.

Do responses return fast when the sheet is open and slow otherwise?
I did not understand the part about server.

**Comment by EnesMBatur** [comment]
I solved the problem my mistake thank you for the answer.
